language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

r_binary_packages:
  - lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
